export const MODULE_METADATA = 'module'
export const REPOSITORY_METADATA = 'repository'
export const ON_MATCH_ALL_METADATA = 'matchAll'
export const ON_PREFIX_METADATA = 'prefix'
export const ON_PRIVATE_PREFIX = 'privatePrefix'
