export const MODULE_METADATA = 'module'
export const REPOSITORY_METADATA = 'repository'
export const ON_MATCH_ALL_METADATA = 'matchAll'
export const ON_PREFIX_METADATA = 'prefix'
export const ON_SUFFIX_METADATA = 'suffix'
export const ON_KEYWORD_METADATA = 'keyword'
export const ON_REGEX_METADATA = 'regex'
export const SCHEDULE_METADATA = 'schedule'
